version: '3.4'

services:
  coremigration:
    image: ${DOCKER_REGISTRY-}coremigration
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Yassine@123